import uuid


def get_restaurants():
    return [
        # ===================== KOREAN (8) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Gaon",
            "name_ko": "가온",
            "name_zh_cn": "嘉温",
            "name_zh_tw": "嘉溫",
            "name_ja": "ガオン",
            "name_es": "Gaon",
            "name_th": "กาออน",
            "name_vi": "Gaon",
            "name_fr": "Gaon",
            "description_en": "Three Michelin-starred Korean fine dining offering modern interpretations of traditional royal court cuisine.",
            "description_ko": "전통 궁중요리를 현대적으로 재해석한 미쉐린 3스타 한식 파인다이닝 레스토랑입니다.",
            "description_zh_cn": "米其林三星韩式高级餐厅，提供传统宫廷料理的现代诠释。",
            "description_zh_tw": "米其林三星韓式高級餐廳，提供傳統宮廷料理的現代詮釋。",
            "description_ja": "伝統的な宮廷料理を現代的に再解釈したミシュラン三つ星の韓国ファインダイニング。",
            "description_es": "Restaurante de alta cocina coreana con tres estrellas Michelin que ofrece interpretaciones modernas de la cocina real tradicional.",
            "description_th": "ร้านอาหารเกาหลีระดับไฟน์ไดนิ่ง 3 ดาวมิชลิน นำเสนออาหารราชสำนักแบบดั้งเดิมในรูปแบบสมัยใหม่",
            "description_vi": "Nhà hàng Hàn Quốc cao cấp 3 sao Michelin với các món ăn cung đình truyền thống được tái hiện hiện đại.",
            "description_fr": "Restaurant gastronomique coréen trois étoiles Michelin proposant des interprétations modernes de la cuisine royale traditionnelle.",
            "category": "korean",
            "price_range": 4,
            "address": "서울특별시 강남구 도산대로 317",
            "latitude": 37.5225,
            "longitude": 127.0390,
            "phone": "02-545-9845",
            "opening_hours": {
                "mon": "12:00-15:00, 18:00-22:00",
                "tue": "12:00-15:00, 18:00-22:00",
                "wed": "12:00-15:00, 18:00-22:00",
                "thu": "12:00-15:00, 18:00-22:00",
                "fri": "12:00-15:00, 18:00-22:00",
                "sat": "12:00-15:00, 18:00-22:00",
                "sun": "Closed"
            },
            "menu_highlights": [
                {"name_en": "Royal Court Tasting Course", "name_ko": "궁중 코스요리", "price": 250000},
                {"name_en": "Seasonal Banchan Set", "name_ko": "계절 반찬 세트", "price": 180000},
                {"name_en": "Korean Beef Bulgogi", "name_ko": "한우 불고기", "price": 120000},
                {"name_en": "Abalone Porridge", "name_ko": "전복죽", "price": 80000},
            ],
            "images": ["/images/placeholder/restaurant_1.jpg"],
            "avg_rating": 4.8,
            "review_count": 187,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Samwon Garden",
            "name_ko": "삼원가든",
            "name_zh_cn": "三元花园",
            "name_zh_tw": "三元花園",
            "name_ja": "サムウォンガーデン",
            "name_es": "Jardín Samwon",
            "name_th": "ซัมวอนการ์เดน",
            "name_vi": "Vườn Samwon",
            "name_fr": "Jardin Samwon",
            "description_en": "Legendary Korean BBQ restaurant established in 1976, famous for premium galbi in a garden setting.",
            "description_ko": "1976년 개업한 전설적인 한우 갈비 전문점으로 정원이 아름다운 레스토랑입니다.",
            "description_zh_cn": "1976年创立的传奇韩式烤肉餐厅，以庭园环境中的优质牛排骨闻名。",
            "description_zh_tw": "1976年創立的傳奇韓式烤肉餐廳，以庭園環境中的優質牛排骨聞名。",
            "description_ja": "1976年創業の伝説的な韓国焼肉レストラン。庭園の中でプレミアムカルビが楽しめます。",
            "description_es": "Legendario restaurante de barbacoa coreana establecido en 1976, famoso por sus costillas premium en un entorno de jardín.",
            "description_th": "ร้านบาร์บีคิวเกาหลีในตำนานก่อตั้งเมื่อปี 1976 มีชื่อเสียงด้านกัลบีพรีเมียมในบรรยากาศสวน",
            "description_vi": "Nhà hàng BBQ Hàn Quốc huyền thoại thành lập năm 1976, nổi tiếng với sườn bò cao cấp trong không gian vườn.",
            "description_fr": "Restaurant légendaire de barbecue coréen fondé en 1976, célèbre pour ses côtes premium dans un cadre de jardin.",
            "category": "korean",
            "price_range": 4,
            "address": "서울특별시 강남구 언주로 835",
            "latitude": 37.5130,
            "longitude": 127.0340,
            "phone": "02-548-3030",
            "opening_hours": {
                "mon": "11:30-22:00",
                "tue": "11:30-22:00",
                "wed": "11:30-22:00",
                "thu": "11:30-22:00",
                "fri": "11:30-22:00",
                "sat": "11:30-22:00",
                "sun": "11:30-22:00"
            },
            "menu_highlights": [
                {"name_en": "Premium Galbi", "name_ko": "생갈비", "price": 68000},
                {"name_en": "Marinated Galbi", "name_ko": "양념갈비", "price": 62000},
                {"name_en": "Naengmyeon", "name_ko": "냉면", "price": 15000},
                {"name_en": "Doenjang Jjigae", "name_ko": "된장찌개", "price": 12000},
            ],
            "images": ["/images/placeholder/restaurant_2.jpg"],
            "avg_rating": 4.5,
            "review_count": 198,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Tosokchon Samgyetang Gangnam",
            "name_ko": "토속촌 삼계탕 강남점",
            "name_zh_cn": "土俗村参鸡汤 江南店",
            "name_zh_tw": "土俗村蔘雞湯 江南店",
            "name_ja": "トソクチョン サムゲタン 江南店",
            "name_es": "Tosokchon Samgyetang Gangnam",
            "name_th": "โทซกชน ซัมเกทัง คังนัม",
            "name_vi": "Tosokchon Samgyetang Gangnam",
            "name_fr": "Tosokchon Samgyetang Gangnam",
            "description_en": "Famous for traditional ginseng chicken soup, a must-visit for authentic Korean health cuisine.",
            "description_ko": "전통 삼계탕으로 유명한 한식 전문점으로 깊은 맛의 보양식을 즐길 수 있습니다.",
            "description_zh_cn": "以传统人参鸡汤闻名，是体验正宗韩国养生美食的必去之地。",
            "description_zh_tw": "以傳統人蔘雞湯聞名，是體驗正宗韓國養生美食的必去之地。",
            "description_ja": "伝統的な参鶏湯で有名な、本格的な韓国の健康料理を味わえる名店。",
            "description_es": "Famoso por su sopa tradicional de pollo con ginseng, una visita obligada para la auténtica cocina saludable coreana.",
            "description_th": "มีชื่อเสียงด้านซุปไก่โสมสมุนไพรแบบดั้งเดิม เป็นที่ต้องไปสำหรับอาหารสุขภาพเกาหลีแท้",
            "description_vi": "Nổi tiếng với món gà hầm sâm truyền thống, điểm đến không thể bỏ qua cho ẩm thực bổ dưỡng Hàn Quốc.",
            "description_fr": "Célèbre pour sa soupe traditionnelle au poulet et au ginseng, un incontournable de la cuisine santé coréenne.",
            "category": "korean",
            "price_range": 3,
            "address": "서울특별시 강남구 강남대로 328",
            "latitude": 37.4970,
            "longitude": 127.0285,
            "phone": "02-555-1236",
            "opening_hours": {
                "mon": "10:00-21:30",
                "tue": "10:00-21:30",
                "wed": "10:00-21:30",
                "thu": "10:00-21:30",
                "fri": "10:00-21:30",
                "sat": "10:00-21:30",
                "sun": "10:00-21:30"
            },
            "menu_highlights": [
                {"name_en": "Samgyetang", "name_ko": "삼계탕", "price": 17000},
                {"name_en": "Black Chicken Samgyetang", "name_ko": "오골계 삼계탕", "price": 23000},
                {"name_en": "Abalone Samgyetang", "name_ko": "전복 삼계탕", "price": 25000},
            ],
            "images": ["/images/placeholder/restaurant_3.jpg"],
            "avg_rating": 4.3,
            "review_count": 156,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Hanilkwan",
            "name_ko": "한일관",
            "name_zh_cn": "韩一馆",
            "name_zh_tw": "韓一館",
            "name_ja": "ハニルグァン",
            "name_es": "Hanilkwan",
            "name_th": "ฮานิลกวัน",
            "name_vi": "Hanilkwan",
            "name_fr": "Hanilkwan",
            "description_en": "A historic Korean restaurant since 1939, known for its signature beef bulgogi and traditional Korean dishes.",
            "description_ko": "1939년부터 이어온 전통 한식당으로 불고기와 갈비탕이 대표 메뉴입니다.",
            "description_zh_cn": "自1939年以来的历史韩国餐厅，以招牌牛肉烤肉和传统韩国菜闻名。",
            "description_zh_tw": "自1939年以來的歷史韓國餐廳，以招牌牛肉烤肉和傳統韓國菜聞名。",
            "description_ja": "1939年創業の歴史ある韓国料理店。看板メニューの牛プルコギと伝統韓国料理で知られています。",
            "description_es": "Un restaurante coreano histórico desde 1939, conocido por su bulgogi de res y platos tradicionales coreanos.",
            "description_th": "ร้านอาหารเกาหลีเก่าแก่ตั้งแต่ปี 1939 มีชื่อเสียงด้านบุลโกกิเนื้อวัวและอาหารเกาหลีดั้งเดิม",
            "description_vi": "Nhà hàng Hàn Quốc lịch sử từ năm 1939, nổi tiếng với bulgogi bò và các món ăn truyền thống.",
            "description_fr": "Restaurant coréen historique depuis 1939, réputé pour son bulgogi de bœuf signature et ses plats traditionnels.",
            "category": "korean",
            "price_range": 3,
            "address": "서울특별시 강남구 압구정로 38길 16",
            "latitude": 37.5270,
            "longitude": 127.0285,
            "phone": "02-543-3100",
            "opening_hours": {
                "mon": "11:30-21:30",
                "tue": "11:30-21:30",
                "wed": "11:30-21:30",
                "thu": "11:30-21:30",
                "fri": "11:30-21:30",
                "sat": "11:30-21:30",
                "sun": "11:30-21:00"
            },
            "menu_highlights": [
                {"name_en": "Beef Bulgogi", "name_ko": "불고기", "price": 45000},
                {"name_en": "Galbitang", "name_ko": "갈비탕", "price": 18000},
                {"name_en": "Japchae", "name_ko": "잡채", "price": 30000},
                {"name_en": "Bibimbap", "name_ko": "비빔밥", "price": 15000},
            ],
            "images": ["/images/placeholder/restaurant_4.jpg"],
            "avg_rating": 4.4,
            "review_count": 142,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Jungsik",
            "name_ko": "정식",
            "name_zh_cn": "正食",
            "name_zh_tw": "正食",
            "name_ja": "ジョンシク",
            "name_es": "Jungsik",
            "name_th": "จองชิก",
            "name_vi": "Jungsik",
            "name_fr": "Jungsik",
            "description_en": "Two Michelin-starred innovative Korean restaurant blending modern techniques with traditional Korean flavors.",
            "description_ko": "미쉐린 2스타 모던 한식 레스토랑으로 전통 한식에 현대적 기법을 접목한 혁신적인 요리를 선보입니다.",
            "description_zh_cn": "米其林二星创新韩式餐厅，将现代技术与传统韩国风味完美融合。",
            "description_zh_tw": "米其林二星創新韓式餐廳，將現代技術與傳統韓國風味完美融合。",
            "description_ja": "ミシュラン二つ星の革新的な韓国料理店。モダンな技法と伝統的な韓国の味わいを融合させています。",
            "description_es": "Restaurante coreano innovador con dos estrellas Michelin que fusiona técnicas modernas con sabores tradicionales coreanos.",
            "description_th": "ร้านอาหารเกาหลี 2 ดาวมิชลิน ผสมผสานเทคนิคสมัยใหม่กับรสชาติเกาหลีดั้งเดิม",
            "description_vi": "Nhà hàng Hàn Quốc sáng tạo 2 sao Michelin kết hợp kỹ thuật hiện đại với hương vị Hàn Quốc truyền thống.",
            "description_fr": "Restaurant coréen innovant deux étoiles Michelin mêlant techniques modernes et saveurs traditionnelles coréennes.",
            "category": "korean",
            "price_range": 4,
            "address": "서울특별시 강남구 선릉로 158길 11",
            "latitude": 37.5240,
            "longitude": 127.0460,
            "phone": "02-517-4654",
            "opening_hours": {
                "mon": "Closed",
                "tue": "12:00-15:00, 18:00-22:00",
                "wed": "12:00-15:00, 18:00-22:00",
                "thu": "12:00-15:00, 18:00-22:00",
                "fri": "12:00-15:00, 18:00-22:00",
                "sat": "12:00-15:00, 18:00-22:00",
                "sun": "Closed"
            },
            "menu_highlights": [
                {"name_en": "Jungsik Tasting Course", "name_ko": "정식 코스", "price": 200000},
                {"name_en": "Bibimbap Reimagined", "name_ko": "정식 비빔밥", "price": 45000},
                {"name_en": "Ganjang Gejang Pasta", "name_ko": "간장게장 파스타", "price": 55000},
                {"name_en": "Kimchi Consommé", "name_ko": "김치 콩소메", "price": 30000},
            ],
            "images": ["/images/placeholder/restaurant_5.jpg"],
            "avg_rating": 4.7,
            "review_count": 165,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Yukjeon Hoekwan",
            "name_ko": "육전회관",
            "name_zh_cn": "肉田会馆",
            "name_zh_tw": "肉田會館",
            "name_ja": "ユクジョンフェグァン",
            "name_es": "Yukjeon Hoekwan",
            "name_th": "ยุกจอนเฮกวัน",
            "name_vi": "Yukjeon Hoekwan",
            "name_fr": "Yukjeon Hoekwan",
            "description_en": "Classic Korean BBQ restaurant in Gangnam specializing in marinated beef ribs and traditional side dishes.",
            "description_ko": "강남 지역 전통 소갈비 전문 한식당으로 정통 양념갈비와 반찬이 일품입니다.",
            "description_zh_cn": "江南地区经典韩式烤肉餐厅，专营腌制牛排骨和传统小菜。",
            "description_zh_tw": "江南地區經典韓式烤肉餐廳，專營醃製牛排骨和傳統小菜。",
            "description_ja": "江南にある伝統的な韓国BBQレストラン。味付けカルビと伝統的なおかずが自慢です。",
            "description_es": "Restaurante clásico de BBQ coreana en Gangnam especializado en costillas de res marinadas y guarniciones tradicionales.",
            "description_th": "ร้านบาร์บีคิวเกาหลีคลาสสิกในคังนัม เชี่ยวชาญซี่โครงเนื้อหมักและเครื่องเคียงแบบดั้งเดิม",
            "description_vi": "Nhà hàng BBQ Hàn Quốc cổ điển ở Gangnam chuyên sườn bò ướp và các món phụ truyền thống.",
            "description_fr": "Restaurant classique de BBQ coréen à Gangnam, spécialisé dans les côtes de bœuf marinées et les accompagnements traditionnels.",
            "category": "korean",
            "price_range": 2,
            "address": "서울특별시 서초구 서초대로77길 54",
            "latitude": 37.4945,
            "longitude": 127.0260,
            "phone": "02-536-3339",
            "opening_hours": {
                "mon": "11:00-22:00",
                "tue": "11:00-22:00",
                "wed": "11:00-22:00",
                "thu": "11:00-22:00",
                "fri": "11:00-22:00",
                "sat": "11:00-22:00",
                "sun": "11:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Marinated Beef Ribs", "name_ko": "양념갈비", "price": 28000},
                {"name_en": "Raw Beef Tartare", "name_ko": "육회", "price": 22000},
                {"name_en": "Galbitang", "name_ko": "갈비탕", "price": 14000},
                {"name_en": "Bulgogi", "name_ko": "불고기", "price": 20000},
            ],
            "images": ["/images/placeholder/restaurant_6.jpg"],
            "avg_rating": 4.2,
            "review_count": 98,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Baekjeong Gangnam",
            "name_ko": "백정 강남점",
            "name_zh_cn": "白丁 江南店",
            "name_zh_tw": "白丁 江南店",
            "name_ja": "ペクジョン 江南店",
            "name_es": "Baekjeong Gangnam",
            "name_th": "แพคจอง คังนัม",
            "name_vi": "Baekjeong Gangnam",
            "name_fr": "Baekjeong Gangnam",
            "description_en": "Popular Korean BBQ chain known for thick-cut pork belly and fun, energetic atmosphere.",
            "description_ko": "두꺼운 삼겹살과 활기찬 분위기로 유명한 인기 한식 고깃집입니다.",
            "description_zh_cn": "以厚切五花肉和欢乐活泼的氛围闻名的人气韩式烤肉连锁店。",
            "description_zh_tw": "以厚切五花肉和歡樂活潑的氛圍聞名的人氣韓式烤肉連鎖店。",
            "description_ja": "厚切り豚バラ肉と楽しく活気ある雰囲気で人気の韓国BBQチェーン。",
            "description_es": "Cadena popular de BBQ coreana conocida por su panceta de cerdo gruesa y su ambiente divertido y enérgico.",
            "description_th": "เชนบาร์บีคิวเกาหลียอดนิยม มีชื่อเสียงด้านหมูสามชั้นหั่นหนาและบรรยากาศสนุกสนาน",
            "description_vi": "Chuỗi BBQ Hàn Quốc nổi tiếng với thịt ba chỉ cắt dày và không khí vui vẻ, sôi động.",
            "description_fr": "Chaîne populaire de BBQ coréen connue pour sa poitrine de porc épaisse et son ambiance amusante et énergique.",
            "category": "korean",
            "price_range": 2,
            "address": "서울특별시 강남구 강남대로 390",
            "latitude": 37.4990,
            "longitude": 127.0290,
            "phone": "02-556-5667",
            "opening_hours": {
                "mon": "11:00-23:00",
                "tue": "11:00-23:00",
                "wed": "11:00-23:00",
                "thu": "11:00-23:00",
                "fri": "11:00-24:00",
                "sat": "11:00-24:00",
                "sun": "11:00-23:00"
            },
            "menu_highlights": [
                {"name_en": "Thick-cut Pork Belly", "name_ko": "두껍삼겹살", "price": 16000},
                {"name_en": "Beef Brisket", "name_ko": "차돌박이", "price": 22000},
                {"name_en": "Spicy Cold Noodles", "name_ko": "비빔냉면", "price": 8000},
                {"name_en": "Egg Steamed", "name_ko": "계란찜", "price": 5000},
            ],
            "images": ["/images/placeholder/restaurant_7.jpg"],
            "avg_rating": 4.1,
            "review_count": 178,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Myeongdong Kyoja Gangnam",
            "name_ko": "명동교자 강남점",
            "name_zh_cn": "明洞饺子 江南店",
            "name_zh_tw": "明洞餃子 江南店",
            "name_ja": "ミョンドンギョジャ 江南店",
            "name_es": "Myeongdong Kyoja Gangnam",
            "name_th": "เมียงดงเคียวจา คังนัม",
            "name_vi": "Myeongdong Kyoja Gangnam",
            "name_fr": "Myeongdong Kyoja Gangnam",
            "description_en": "Beloved noodle and dumpling house famous for kalguksu and handmade mandu at affordable prices.",
            "description_ko": "칼국수와 수제 만두로 사랑받는 대표적인 서민 맛집입니다.",
            "description_zh_cn": "深受喜爱的面条和饺子店，以价格实惠的刀削面和手工饺子闻名。",
            "description_zh_tw": "深受喜愛的麵條和餃子店，以價格實惠的刀削麵和手工餃子聞名。",
            "description_ja": "カルグクスと手作りマンドゥで愛される手頃な価格の麺・餃子店。",
            "description_es": "Querida casa de fideos y dumplings famosa por kalguksu y mandu hechos a mano a precios asequibles.",
            "description_th": "ร้านก๋วยเตี๋ยวและเกี๊ยวยอดนิยม มีชื่อเสียงด้านคัลกุกซูและมันดูทำมือในราคาย่อมเยา",
            "description_vi": "Quán mì và sủi cảo nổi tiếng với kalguksu và mandu thủ công giá phải chăng.",
            "description_fr": "Restaurant de nouilles et raviolis apprécié, célèbre pour ses kalguksu et mandu faits main à prix abordables.",
            "category": "korean",
            "price_range": 1,
            "address": "서울특별시 강남구 테헤란로 142",
            "latitude": 37.5010,
            "longitude": 127.0365,
            "phone": "02-558-9488",
            "opening_hours": {
                "mon": "10:30-21:30",
                "tue": "10:30-21:30",
                "wed": "10:30-21:30",
                "thu": "10:30-21:30",
                "fri": "10:30-21:30",
                "sat": "10:30-21:30",
                "sun": "10:30-21:00"
            },
            "menu_highlights": [
                {"name_en": "Kalguksu", "name_ko": "칼국수", "price": 10000},
                {"name_en": "Mandu", "name_ko": "만두", "price": 10000},
                {"name_en": "Bibim Guksu", "name_ko": "비빔국수", "price": 10000},
                {"name_en": "Kong-guksu", "name_ko": "콩국수", "price": 11000},
            ],
            "images": ["/images/placeholder/restaurant_8.jpg"],
            "avg_rating": 4.3,
            "review_count": 167,
            "is_active": True,
        },
        # ===================== JAPANESE (4) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Sushi Koji",
            "name_ko": "스시 코지",
            "name_zh_cn": "寿司幸治",
            "name_zh_tw": "壽司幸治",
            "name_ja": "鮨 幸治",
            "name_es": "Sushi Koji",
            "name_th": "ซูชิ โคจิ",
            "name_vi": "Sushi Koji",
            "name_fr": "Sushi Koji",
            "description_en": "Premium omakase sushi restaurant in Cheongdam-dong serving fresh seasonal fish flown in from Tsukiji Market.",
            "description_ko": "청담동에 위치한 프리미엄 오마카세 스시 전문점으로 츠키지 공수 신선한 생선을 제공합니다.",
            "description_zh_cn": "位于清潭洞的高级寿司料理店，供应从筑地市场空运的新鲜时令鱼类。",
            "description_zh_tw": "位於清潭洞的高級壽司料理店，供應從築地市場空運的新鮮時令魚類。",
            "description_ja": "清潭洞にあるプレミアムおまかせ寿司店。築地から空輸される新鮮な旬の魚を提供。",
            "description_es": "Restaurante premium de sushi omakase en Cheongdam-dong que sirve pescado fresco de temporada del mercado de Tsukiji.",
            "description_th": "ร้านซูชิโอมากาเสะพรีเมียมในชองดัมดง เสิร์ฟปลาสดตามฤดูกาลจากตลาดซึกิจิ",
            "description_vi": "Nhà hàng sushi omakase cao cấp ở Cheongdam-dong phục vụ cá tươi theo mùa từ chợ Tsukiji.",
            "description_fr": "Restaurant de sushi omakase premium à Cheongdam-dong servant du poisson frais de saison du marché de Tsukiji.",
            "category": "japanese",
            "price_range": 4,
            "address": "서울특별시 강남구 도산대로 521",
            "latitude": 37.5225,
            "longitude": 127.0420,
            "phone": "02-511-2345",
            "opening_hours": {
                "mon": "Closed",
                "tue": "12:00-14:30, 18:00-22:00",
                "wed": "12:00-14:30, 18:00-22:00",
                "thu": "12:00-14:30, 18:00-22:00",
                "fri": "12:00-14:30, 18:00-22:00",
                "sat": "12:00-14:30, 18:00-22:00",
                "sun": "12:00-14:30, 18:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Lunch Omakase", "name_ko": "런치 오마카세", "price": 120000},
                {"name_en": "Dinner Omakase", "name_ko": "디너 오마카세", "price": 250000},
                {"name_en": "Premium Sake Pairing", "name_ko": "프리미엄 사케 페어링", "price": 80000},
            ],
            "images": ["/images/placeholder/restaurant_9.jpg"],
            "avg_rating": 4.7,
            "review_count": 89,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Ramen Yamamoto",
            "name_ko": "라멘 야마모토",
            "name_zh_cn": "拉面山本",
            "name_zh_tw": "拉麵山本",
            "name_ja": "ラーメン山本",
            "name_es": "Ramen Yamamoto",
            "name_th": "ราเมน ยามาโมโตะ",
            "name_vi": "Ramen Yamamoto",
            "name_fr": "Ramen Yamamoto",
            "description_en": "Authentic Japanese ramen shop in Gangnam serving rich tonkotsu and shoyu ramen with handmade noodles.",
            "description_ko": "강남의 정통 일본 라멘 전문점으로 진한 돈코츠와 쇼유 라멘을 수제 면으로 제공합니다.",
            "description_zh_cn": "江南的正宗日式拉面店，供应浓郁的豚骨和酱油拉面，配以手工面条。",
            "description_zh_tw": "江南的正宗日式拉麵店，供應濃郁的豚骨和醬油拉麵，配以手工麵條。",
            "description_ja": "江南にある本格的な日本のラーメン店。濃厚なとんこつと醤油ラーメンを手打ち麺で提供。",
            "description_es": "Auténtica tienda de ramen japonés en Gangnam que sirve ramen tonkotsu y shoyu con fideos hechos a mano.",
            "description_th": "ร้านราเมนญี่ปุ่นแท้ในคังนัม เสิร์ฟราเมนทงคตสึและโชยุเข้มข้นกับเส้นทำมือ",
            "description_vi": "Quán ramen Nhật Bản chính hiệu ở Gangnam phục vụ ramen tonkotsu và shoyu đậm đà với mì thủ công.",
            "description_fr": "Authentique restaurant de ramen japonais à Gangnam servant des ramen tonkotsu et shoyu riches avec des nouilles faites main.",
            "category": "japanese",
            "price_range": 1,
            "address": "서울특별시 강남구 역삼로 180",
            "latitude": 37.5005,
            "longitude": 127.0370,
            "phone": "02-555-8901",
            "opening_hours": {
                "mon": "11:00-21:30",
                "tue": "11:00-21:30",
                "wed": "11:00-21:30",
                "thu": "11:00-21:30",
                "fri": "11:00-22:00",
                "sat": "11:00-22:00",
                "sun": "11:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Tonkotsu Ramen", "name_ko": "돈코츠 라멘", "price": 12000},
                {"name_en": "Shoyu Ramen", "name_ko": "쇼유 라멘", "price": 11000},
                {"name_en": "Chashu Don", "name_ko": "차슈동", "price": 10000},
                {"name_en": "Gyoza", "name_ko": "교자", "price": 6000},
            ],
            "images": ["/images/placeholder/restaurant_10.jpg"],
            "avg_rating": 4.2,
            "review_count": 134,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Izakaya Maru",
            "name_ko": "이자카야 마루",
            "name_zh_cn": "居酒屋 丸",
            "name_zh_tw": "居酒屋 丸",
            "name_ja": "居酒屋 まる",
            "name_es": "Izakaya Maru",
            "name_th": "อิซากายะ มารุ",
            "name_vi": "Izakaya Maru",
            "name_fr": "Izakaya Maru",
            "description_en": "Cozy Japanese izakaya in Seocho offering grilled skewers, sashimi, and a wide selection of sake.",
            "description_ko": "서초의 아늑한 일본식 이자카야로 꼬치구이, 사시미, 다양한 사케를 즐길 수 있습니다.",
            "description_zh_cn": "位于瑞草的温馨日式居酒屋，提供烤串、刺身和丰富的清酒选择。",
            "description_zh_tw": "位於瑞草的溫馨日式居酒屋，提供烤串、刺身和豐富的清酒選擇。",
            "description_ja": "瑞草にある居心地の良い居酒屋。焼き鳥、刺身、豊富な日本酒を楽しめます。",
            "description_es": "Acogedor izakaya japonés en Seocho que ofrece brochetas a la parrilla, sashimi y una amplia selección de sake.",
            "description_th": "อิซากายะญี่ปุ่นอบอุ่นในซอโช เสิร์ฟไม้เสียบย่าง ซาชิมิ และสาเกหลากหลาย",
            "description_vi": "Quán izakaya Nhật Bản ấm cúng ở Seocho với xiên nướng, sashimi và nhiều loại sake.",
            "description_fr": "Izakaya japonais chaleureux à Seocho proposant des brochettes grillées, sashimi et une large sélection de saké.",
            "category": "japanese",
            "price_range": 2,
            "address": "서울특별시 서초구 서초대로78길 42",
            "latitude": 37.4930,
            "longitude": 127.0240,
            "phone": "02-583-4456",
            "opening_hours": {
                "mon": "17:00-01:00",
                "tue": "17:00-01:00",
                "wed": "17:00-01:00",
                "thu": "17:00-01:00",
                "fri": "17:00-02:00",
                "sat": "17:00-02:00",
                "sun": "17:00-24:00"
            },
            "menu_highlights": [
                {"name_en": "Yakitori Platter", "name_ko": "야키토리 모듬", "price": 25000},
                {"name_en": "Assorted Sashimi", "name_ko": "모듬 사시미", "price": 35000},
                {"name_en": "Takoyaki", "name_ko": "타코야키", "price": 9000},
                {"name_en": "Edamame", "name_ko": "에다마메", "price": 7000},
                {"name_en": "Premium Sake Set", "name_ko": "프리미엄 사케 세트", "price": 30000},
            ],
            "images": ["/images/placeholder/restaurant_11.jpg"],
            "avg_rating": 4.3,
            "review_count": 112,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Katsu Sando Gangnam",
            "name_ko": "카츠 산도 강남점",
            "name_zh_cn": "炸猪排三明治 江南店",
            "name_zh_tw": "炸豬排三明治 江南店",
            "name_ja": "カツサンド 江南店",
            "name_es": "Katsu Sando Gangnam",
            "name_th": "คัตสึ ซันโด คังนัม",
            "name_vi": "Katsu Sando Gangnam",
            "name_fr": "Katsu Sando Gangnam",
            "description_en": "Trendy Japanese tonkatsu restaurant serving premium pork cutlets with homemade cabbage and tonkatsu sauce.",
            "description_ko": "프리미엄 돈까스를 수제 양배추 샐러드와 특제 소스로 제공하는 트렌디한 일식 돈까스 전문점입니다.",
            "description_zh_cn": "时尚的日式炸猪排餐厅，供应优质猪排配自制卷心菜和猪排酱。",
            "description_zh_tw": "時尚的日式炸豬排餐廳，供應優質豬排配自製高麗菜和豬排醬。",
            "description_ja": "プレミアムとんかつを自家製キャベツとソースで提供するトレンディなとんかつ専門店。",
            "description_es": "Restaurante de tonkatsu japonés de moda que sirve chuletas de cerdo premium con repollo casero y salsa tonkatsu.",
            "description_th": "ร้านทงคัตสึญี่ปุ่นทันสมัย เสิร์ฟหมูชุบแป้งทอดพรีเมียมกับกะหล่ำปลีและซอสทงคัตสึทำเอง",
            "description_vi": "Nhà hàng tonkatsu Nhật Bản thời thượng phục vụ cốt lết heo cao cấp với bắp cải và sốt tonkatsu tự làm.",
            "description_fr": "Restaurant de tonkatsu japonais branché servant des côtelettes de porc premium avec chou maison et sauce tonkatsu.",
            "category": "japanese",
            "price_range": 2,
            "address": "서울특별시 강남구 테헤란로 210",
            "latitude": 37.5015,
            "longitude": 127.0410,
            "phone": "02-568-3321",
            "opening_hours": {
                "mon": "11:00-21:00",
                "tue": "11:00-21:00",
                "wed": "11:00-21:00",
                "thu": "11:00-21:00",
                "fri": "11:00-21:30",
                "sat": "11:00-21:30",
                "sun": "11:00-20:30"
            },
            "menu_highlights": [
                {"name_en": "Premium Hire Katsu", "name_ko": "프리미엄 히레카츠", "price": 18000},
                {"name_en": "Rosu Katsu", "name_ko": "로스카츠", "price": 15000},
                {"name_en": "Cheese Katsu", "name_ko": "치즈카츠", "price": 17000},
                {"name_en": "Katsu Sando", "name_ko": "카츠산도", "price": 12000},
            ],
            "images": ["/images/placeholder/restaurant_12.jpg"],
            "avg_rating": 4.1,
            "review_count": 95,
            "is_active": True,
        },
        # ===================== CHINESE (3) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Ho Lee Chow Gangnam",
            "name_ko": "호리초우 강남점",
            "name_zh_cn": "好利秋 江南店",
            "name_zh_tw": "好利秋 江南店",
            "name_ja": "ホリチョウ 江南店",
            "name_es": "Ho Lee Chow Gangnam",
            "name_th": "โฮลีโชว์ คังนัม",
            "name_vi": "Ho Lee Chow Gangnam",
            "name_fr": "Ho Lee Chow Gangnam",
            "description_en": "Upscale Chinese restaurant in Gangnam serving authentic Cantonese and Sichuan cuisine with premium ingredients.",
            "description_ko": "강남에 위치한 고급 중식 레스토랑으로 정통 광둥식과 사천식 요리를 프리미엄 식재료로 선보입니다.",
            "description_zh_cn": "位于江南的高档中餐厅，以优质食材供应正宗粤菜和川菜。",
            "description_zh_tw": "位於江南的高檔中餐廳，以優質食材供應正宗粵菜和川菜。",
            "description_ja": "江南にある高級中華レストラン。プレミアム食材を使った本格的な広東・四川料理を提供。",
            "description_es": "Restaurante chino de lujo en Gangnam que sirve auténtica cocina cantonesa y sichuanesa con ingredientes premium.",
            "description_th": "ร้านอาหารจีนหรูในคังนัม เสิร์ฟอาหารกวางตุ้งและเสฉวนแท้ด้วยวัตถุดิบพรีเมียม",
            "description_vi": "Nhà hàng Trung Hoa cao cấp ở Gangnam phục vụ ẩm thực Quảng Đông và Tứ Xuyên chính hiệu.",
            "description_fr": "Restaurant chinois haut de gamme à Gangnam servant une authentique cuisine cantonaise et sichuanaise.",
            "category": "chinese",
            "price_range": 3,
            "address": "서울특별시 강남구 논현로 164길 23",
            "latitude": 37.5175,
            "longitude": 127.0340,
            "phone": "02-546-7788",
            "opening_hours": {
                "mon": "11:30-22:00",
                "tue": "11:30-22:00",
                "wed": "11:30-22:00",
                "thu": "11:30-22:00",
                "fri": "11:30-22:30",
                "sat": "11:30-22:30",
                "sun": "11:30-21:30"
            },
            "menu_highlights": [
                {"name_en": "Peking Duck", "name_ko": "베이징덕", "price": 68000},
                {"name_en": "Mapo Tofu", "name_ko": "마파두부", "price": 22000},
                {"name_en": "Dim Sum Platter", "name_ko": "딤섬 모듬", "price": 38000},
                {"name_en": "Kung Pao Chicken", "name_ko": "궁바오지딩", "price": 28000},
                {"name_en": "XO Fried Rice", "name_ko": "XO 볶음밥", "price": 18000},
            ],
            "images": ["/images/placeholder/restaurant_13.jpg"],
            "avg_rating": 4.4,
            "review_count": 123,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Haidilao Gangnam",
            "name_ko": "하이디라오 강남점",
            "name_zh_cn": "海底捞 江南店",
            "name_zh_tw": "海底撈 江南店",
            "name_ja": "ハイディラオ 江南店",
            "name_es": "Haidilao Gangnam",
            "name_th": "ไห่ตี่เลา คังนัม",
            "name_vi": "Haidilao Gangnam",
            "name_fr": "Haidilao Gangnam",
            "description_en": "World-famous Chinese hot pot chain known for exceptional service, fresh ingredients, and noodle-pulling shows.",
            "description_ko": "뛰어난 서비스와 신선한 재료, 면발쇼로 유명한 세계적인 중국 훠궈 체인점입니다.",
            "description_zh_cn": "世界知名的中国火锅连锁店，以卓越的服务、新鲜食材和拉面表演闻名。",
            "description_zh_tw": "世界知名的中國火鍋連鎖店，以卓越的服務、新鮮食材和拉麵表演聞名。",
            "description_ja": "卓越したサービス、新鮮な食材、麺引きショーで世界的に有名な中国火鍋チェーン。",
            "description_es": "Cadena mundialmente famosa de hot pot chino conocida por su excepcional servicio, ingredientes frescos y espectáculo de fideos.",
            "description_th": "เชนหม้อไฟจีนชื่อดังระดับโลก มีชื่อเสียงด้านบริการยอดเยี่ยม วัตถุดิบสด และโชว์ดึงเส้นก๋วยเตี๋ยว",
            "description_vi": "Chuỗi lẩu Trung Quốc nổi tiếng thế giới với dịch vụ xuất sắc, nguyên liệu tươi và biểu diễn kéo mì.",
            "description_fr": "Chaîne de fondue chinoise mondialement connue pour son service exceptionnel, ses ingrédients frais et ses spectacles de nouilles.",
            "category": "chinese",
            "price_range": 2,
            "address": "서울특별시 강남구 강남대로 452",
            "latitude": 37.5020,
            "longitude": 127.0265,
            "phone": "02-553-5558",
            "opening_hours": {
                "mon": "10:00-06:00",
                "tue": "10:00-06:00",
                "wed": "10:00-06:00",
                "thu": "10:00-06:00",
                "fri": "10:00-06:00",
                "sat": "10:00-06:00",
                "sun": "10:00-06:00"
            },
            "menu_highlights": [
                {"name_en": "Signature Hot Pot Set", "name_ko": "시그니처 훠궈 세트", "price": 25000},
                {"name_en": "Sliced Beef Platter", "name_ko": "소고기 모듬", "price": 22000},
                {"name_en": "Handmade Noodles", "name_ko": "수제 면", "price": 8000},
                {"name_en": "Seafood Platter", "name_ko": "해산물 모듬", "price": 30000},
            ],
            "images": ["/images/placeholder/restaurant_14.jpg"],
            "avg_rating": 4.3,
            "review_count": 189,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Jajangmyeon House Seocho",
            "name_ko": "짜장면하우스 서초점",
            "name_zh_cn": "炸酱面屋 瑞草店",
            "name_zh_tw": "炸醬麵屋 瑞草店",
            "name_ja": "ジャジャンミョンハウス 瑞草店",
            "name_es": "Casa Jajangmyeon Seocho",
            "name_th": "จาจังมยอนเฮาส์ ซอโช",
            "name_vi": "Nhà Jajangmyeon Seocho",
            "name_fr": "Maison Jajangmyeon Seocho",
            "description_en": "Popular Chinese-Korean restaurant specializing in jajangmyeon, jjamppong, and tangsuyuk at great value.",
            "description_ko": "짜장면, 짬뽕, 탕수육을 합리적인 가격에 즐길 수 있는 인기 중화요리 전문점입니다.",
            "description_zh_cn": "专营炸酱面、炒码面和糖醋肉的人气中韩餐厅，性价比极高。",
            "description_zh_tw": "專營炸醬麵、炒碼麵和糖醋肉的人氣中韓餐廳，性價比極高。",
            "description_ja": "ジャジャンミョン、チャンポン、タンスユクを手頃な価格で楽しめる人気の中韓料理店。",
            "description_es": "Popular restaurante chino-coreano especializado en jajangmyeon, jjamppong y tangsuyuk con excelente relación calidad-precio.",
            "description_th": "ร้านอาหารจีน-เกาหลียอดนิยม เชี่ยวชาญจาจังมยอน จัมปง และทังซูยุก คุ้มค่ามาก",
            "description_vi": "Nhà hàng Trung-Hàn nổi tiếng chuyên jajangmyeon, jjamppong và tangsuyuk với giá hấp dẫn.",
            "description_fr": "Restaurant populaire sino-coréen spécialisé dans le jajangmyeon, jjamppong et tangsuyuk à excellent rapport qualité-prix.",
            "category": "chinese",
            "price_range": 1,
            "address": "서울특별시 서초구 서초중앙로 188",
            "latitude": 37.4910,
            "longitude": 127.0175,
            "phone": "02-522-3456",
            "opening_hours": {
                "mon": "10:30-21:30",
                "tue": "10:30-21:30",
                "wed": "10:30-21:30",
                "thu": "10:30-21:30",
                "fri": "10:30-22:00",
                "sat": "10:30-22:00",
                "sun": "10:30-21:00"
            },
            "menu_highlights": [
                {"name_en": "Jajangmyeon", "name_ko": "짜장면", "price": 7000},
                {"name_en": "Jjamppong", "name_ko": "짬뽕", "price": 8000},
                {"name_en": "Tangsuyuk", "name_ko": "탕수육", "price": 18000},
                {"name_en": "Fried Rice", "name_ko": "볶음밥", "price": 8000},
            ],
            "images": ["/images/placeholder/restaurant_15.jpg"],
            "avg_rating": 4.0,
            "review_count": 145,
            "is_active": True,
        },
        # ===================== WESTERN (4) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Born & Bred Gangnam",
            "name_ko": "본앤브레드 강남점",
            "name_zh_cn": "Born & Bred 江南店",
            "name_zh_tw": "Born & Bred 江南店",
            "name_ja": "ボーン＆ブレッド 江南店",
            "name_es": "Born & Bred Gangnam",
            "name_th": "บอร์น แอนด์ เบรด คังนัม",
            "name_vi": "Born & Bred Gangnam",
            "name_fr": "Born & Bred Gangnam",
            "description_en": "Premium steakhouse in Gangnam specializing in dry-aged Korean beef with sophisticated wine pairings.",
            "description_ko": "드라이에이징 한우 스테이크와 세련된 와인 페어링을 선보이는 강남 프리미엄 스테이크하우스입니다.",
            "description_zh_cn": "江南的高档牛排馆，专营干式熟成韩牛配精致的葡萄酒搭配。",
            "description_zh_tw": "江南的高檔牛排館，專營乾式熟成韓牛配精緻的葡萄酒搭配。",
            "description_ja": "ドライエイジング韓牛ステーキと洗練されたワインペアリングを提供する江南のプレミアムステーキハウス。",
            "description_es": "Steakhouse premium en Gangnam especializado en carne coreana madurada en seco con maridajes de vino sofisticados.",
            "description_th": "สเต็กเฮาส์พรีเมียมในคังนัม เชี่ยวชาญเนื้อเกาหลีดรายเอจกับไวน์จับคู่อย่างประณีต",
            "description_vi": "Nhà hàng bít tết cao cấp ở Gangnam chuyên bò Hàn Quốc ủ khô với rượu vang kết hợp tinh tế.",
            "description_fr": "Steakhouse premium à Gangnam spécialisé dans le bœuf coréen maturé à sec avec des accords mets-vins sophistiqués.",
            "category": "western",
            "price_range": 4,
            "address": "서울특별시 강남구 선릉로 831",
            "latitude": 37.5140,
            "longitude": 127.0485,
            "phone": "02-540-4400",
            "opening_hours": {
                "mon": "11:30-22:00",
                "tue": "11:30-22:00",
                "wed": "11:30-22:00",
                "thu": "11:30-22:00",
                "fri": "11:30-23:00",
                "sat": "11:30-23:00",
                "sun": "11:30-21:30"
            },
            "menu_highlights": [
                {"name_en": "Dry-aged Korean Beef Ribeye", "name_ko": "드라이에이징 한우 립아이", "price": 95000},
                {"name_en": "Tomahawk Steak", "name_ko": "토마호크 스테이크", "price": 180000},
                {"name_en": "Truffle Mac & Cheese", "name_ko": "트러플 맥앤치즈", "price": 28000},
                {"name_en": "Caesar Salad", "name_ko": "시저 샐러드", "price": 22000},
            ],
            "images": ["/images/placeholder/restaurant_16.jpg"],
            "avg_rating": 4.5,
            "review_count": 156,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Le Bistro de Seoul",
            "name_ko": "르 비스트로 드 서울",
            "name_zh_cn": "首尔小酒馆",
            "name_zh_tw": "首爾小酒館",
            "name_ja": "ル・ビストロ・ド・ソウル",
            "name_es": "Le Bistro de Seúl",
            "name_th": "เลอ บิสโทร เดอ โซล",
            "name_vi": "Le Bistro de Seoul",
            "name_fr": "Le Bistro de Séoul",
            "description_en": "Charming French bistro in Seocho offering classic French cuisine with Korean seasonal ingredients.",
            "description_ko": "한국 제철 식재료로 프렌치 클래식 요리를 선보이는 서초의 매력적인 프렌치 비스트로입니다.",
            "description_zh_cn": "位于瑞草的迷人法式小酒馆，以韩国时令食材制作经典法国菜。",
            "description_zh_tw": "位於瑞草的迷人法式小酒館，以韓國時令食材製作經典法國菜。",
            "description_ja": "韓国の旬の食材を使ったクラシックフランス料理を提供する瑞草の魅力的なフレンチビストロ。",
            "description_es": "Encantador bistró francés en Seocho que ofrece cocina francesa clásica con ingredientes estacionales coreanos.",
            "description_th": "บิสโทรฝรั่งเศสน่ารักในซอโช นำเสนออาหารฝรั่งเศสคลาสสิกด้วยวัตถุดิบตามฤดูกาลเกาหลี",
            "description_vi": "Quán bistro Pháp duyên dáng ở Seocho với ẩm thực Pháp cổ điển kết hợp nguyên liệu theo mùa Hàn Quốc.",
            "description_fr": "Charmant bistro français à Seocho proposant une cuisine française classique avec des ingrédients coréens de saison.",
            "category": "western",
            "price_range": 3,
            "address": "서울특별시 서초구 사평대로 68",
            "latitude": 37.5045,
            "longitude": 127.0035,
            "phone": "02-595-1234",
            "opening_hours": {
                "mon": "Closed",
                "tue": "11:30-15:00, 18:00-22:00",
                "wed": "11:30-15:00, 18:00-22:00",
                "thu": "11:30-15:00, 18:00-22:00",
                "fri": "11:30-15:00, 18:00-22:30",
                "sat": "11:30-15:00, 18:00-22:30",
                "sun": "11:30-15:00, 18:00-21:30"
            },
            "menu_highlights": [
                {"name_en": "Duck Confit", "name_ko": "오리 콩피", "price": 38000},
                {"name_en": "Steak Frites", "name_ko": "스테이크 프리트", "price": 42000},
                {"name_en": "French Onion Soup", "name_ko": "프렌치 어니언 수프", "price": 15000},
                {"name_en": "Crème Brûlée", "name_ko": "크렘 브륄레", "price": 14000},
            ],
            "images": ["/images/placeholder/restaurant_17.jpg"],
            "avg_rating": 4.4,
            "review_count": 87,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Trattoria Molto Gangnam",
            "name_ko": "트라토리아 몰토 강남",
            "name_zh_cn": "Molto意大利餐厅 江南",
            "name_zh_tw": "Molto義大利餐廳 江南",
            "name_ja": "トラットリア モルト 江南",
            "name_es": "Trattoria Molto Gangnam",
            "name_th": "ทราตโตเรีย มอลโต คังนัม",
            "name_vi": "Trattoria Molto Gangnam",
            "name_fr": "Trattoria Molto Gangnam",
            "description_en": "Authentic Italian trattoria serving handmade pasta, wood-fired pizza, and imported Italian wines.",
            "description_ko": "수제 파스타, 화덕 피자, 이탈리아 수입 와인을 즐길 수 있는 정통 이탈리안 트라토리아입니다.",
            "description_zh_cn": "正宗意大利小餐馆，供应手工意面、柴火披萨和进口意大利葡萄酒。",
            "description_zh_tw": "正宗義大利小餐館，供應手工義大利麵、柴火披薩和進口義大利葡萄酒。",
            "description_ja": "手打ちパスタ、薪窯ピザ、イタリア産ワインを提供する本格イタリアントラットリア。",
            "description_es": "Auténtica trattoria italiana que sirve pasta artesanal, pizza al horno de leña y vinos italianos importados.",
            "description_th": "ร้านอาหารอิตาเลียนแท้ เสิร์ฟพาสต้าทำมือ พิซซาเตาฟืน และไวน์อิตาลีนำเข้า",
            "description_vi": "Trattoria Ý chính hiệu phục vụ pasta thủ công, pizza lò củi và rượu vang Ý nhập khẩu.",
            "description_fr": "Authentique trattoria italienne servant des pâtes faites main, pizzas au feu de bois et vins italiens importés.",
            "category": "western",
            "price_range": 3,
            "address": "서울특별시 강남구 도산대로 114",
            "latitude": 37.5160,
            "longitude": 127.0300,
            "phone": "02-544-6677",
            "opening_hours": {
                "mon": "11:30-22:00",
                "tue": "11:30-22:00",
                "wed": "11:30-22:00",
                "thu": "11:30-22:00",
                "fri": "11:30-23:00",
                "sat": "11:30-23:00",
                "sun": "11:30-21:30"
            },
            "menu_highlights": [
                {"name_en": "Truffle Cream Pasta", "name_ko": "트러플 크림 파스타", "price": 28000},
                {"name_en": "Margherita Pizza", "name_ko": "마르게리타 피자", "price": 22000},
                {"name_en": "Osso Buco", "name_ko": "오소부코", "price": 45000},
                {"name_en": "Tiramisu", "name_ko": "티라미수", "price": 14000},
            ],
            "images": ["/images/placeholder/restaurant_18.jpg"],
            "avg_rating": 4.3,
            "review_count": 113,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Burger B Gangnam",
            "name_ko": "버거B 강남점",
            "name_zh_cn": "Burger B 江南店",
            "name_zh_tw": "Burger B 江南店",
            "name_ja": "バーガーB 江南店",
            "name_es": "Burger B Gangnam",
            "name_th": "เบอร์เกอร์ บี คังนัม",
            "name_vi": "Burger B Gangnam",
            "name_fr": "Burger B Gangnam",
            "description_en": "Gourmet burger restaurant known for premium beef patties, craft beers, and creative burger combinations.",
            "description_ko": "프리미엄 소고기 패티와 크래프트 맥주, 창의적인 버거 조합으로 유명한 수제 버거 전문점입니다.",
            "description_zh_cn": "以优质牛肉饼、精酿啤酒和创意汉堡组合闻名的美食汉堡餐厅。",
            "description_zh_tw": "以優質牛肉餅、精釀啤酒和創意漢堡組合聞名的美食漢堡餐廳。",
            "description_ja": "プレミアムビーフパティ、クラフトビール、クリエイティブなバーガーの組み合わせで知られるグルメバーガー店。",
            "description_es": "Restaurante de hamburguesas gourmet conocido por sus patties de res premium, cervezas artesanales y combinaciones creativas.",
            "description_th": "ร้านเบอร์เกอร์กูร์เมต์ มีชื่อเสียงด้านแพตตี้เนื้อพรีเมียม เบียร์คราฟต์ และเบอร์เกอร์สร้างสรรค์",
            "description_vi": "Nhà hàng burger cao cấp nổi tiếng với patty bò thượng hạng, bia thủ công và sáng tạo burger.",
            "description_fr": "Restaurant de burgers gastronomiques réputé pour ses steaks hachés premium, bières artisanales et créations originales.",
            "category": "western",
            "price_range": 2,
            "address": "서울특별시 강남구 강남대로 358",
            "latitude": 37.4980,
            "longitude": 127.0290,
            "phone": "02-557-8282",
            "opening_hours": {
                "mon": "11:00-22:00",
                "tue": "11:00-22:00",
                "wed": "11:00-22:00",
                "thu": "11:00-22:00",
                "fri": "11:00-23:00",
                "sat": "11:00-23:00",
                "sun": "11:00-21:30"
            },
            "menu_highlights": [
                {"name_en": "Classic Cheese Burger", "name_ko": "클래식 치즈 버거", "price": 14000},
                {"name_en": "Truffle Burger", "name_ko": "트러플 버거", "price": 18000},
                {"name_en": "Sweet Potato Fries", "name_ko": "고구마 프라이", "price": 6000},
                {"name_en": "Craft Beer", "name_ko": "크래프트 맥주", "price": 8000},
            ],
            "images": ["/images/placeholder/restaurant_19.jpg"],
            "avg_rating": 4.2,
            "review_count": 167,
            "is_active": True,
        },
        # ===================== CAFE (4) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Cafe de Flore Gangnam",
            "name_ko": "카페 드 플로르 강남",
            "name_zh_cn": "花神咖啡馆 江南",
            "name_zh_tw": "花神咖啡館 江南",
            "name_ja": "カフェ・ド・フロール 江南",
            "name_es": "Café de Flore Gangnam",
            "name_th": "กาเฟ เดอ ฟลอร์ คังนัม",
            "name_vi": "Café de Flore Gangnam",
            "name_fr": "Café de Flore Gangnam",
            "description_en": "Elegant Parisian-style café in Gangnam offering specialty coffee, French pastries, and a refined ambiance.",
            "description_ko": "스페셜티 커피와 프렌치 페이스트리를 우아한 파리지앵 분위기에서 즐길 수 있는 강남의 카페입니다.",
            "description_zh_cn": "江南优雅的巴黎风格咖啡馆，提供精品咖啡、法式糕点和精致氛围。",
            "description_zh_tw": "江南優雅的巴黎風格咖啡館，提供精品咖啡、法式糕點和精緻氛圍。",
            "description_ja": "スペシャルティコーヒー、フレンチペストリー、洗練された雰囲気を楽しめる江南のパリ風カフェ。",
            "description_es": "Elegante café de estilo parisino en Gangnam que ofrece café de especialidad, pastelería francesa y un ambiente refinado.",
            "description_th": "คาเฟ่สไตล์ปารีสหรูหราในคังนัม เสิร์ฟกาแฟพิเศษ เพสตรี้ฝรั่งเศส และบรรยากาศหรูหรา",
            "description_vi": "Quán cà phê phong cách Paris thanh lịch ở Gangnam với cà phê đặc sản, bánh ngọt Pháp và không gian tinh tế.",
            "description_fr": "Élégant café parisien à Gangnam proposant café de spécialité, pâtisseries françaises et une ambiance raffinée.",
            "category": "cafe",
            "price_range": 2,
            "address": "서울특별시 강남구 압구정로 46길 50",
            "latitude": 37.5260,
            "longitude": 127.0330,
            "phone": "02-549-3355",
            "opening_hours": {
                "mon": "08:00-22:00",
                "tue": "08:00-22:00",
                "wed": "08:00-22:00",
                "thu": "08:00-22:00",
                "fri": "08:00-23:00",
                "sat": "09:00-23:00",
                "sun": "09:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Single Origin Pour Over", "name_ko": "싱글 오리진 핸드드립", "price": 9000},
                {"name_en": "Croissant", "name_ko": "크루아상", "price": 6000},
                {"name_en": "Croque Monsieur", "name_ko": "크로크 무슈", "price": 15000},
                {"name_en": "Matcha Latte", "name_ko": "말차 라떼", "price": 7500},
            ],
            "images": ["/images/placeholder/restaurant_20.jpg"],
            "avg_rating": 4.4,
            "review_count": 132,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Anthracite Coffee Seocho",
            "name_ko": "앤트러사이트 커피 서초",
            "name_zh_cn": "Anthracite咖啡 瑞草",
            "name_zh_tw": "Anthracite咖啡 瑞草",
            "name_ja": "アンスラサイトコーヒー 瑞草",
            "name_es": "Anthracite Coffee Seocho",
            "name_th": "แอนทราไซต์ คอฟฟี่ ซอโช",
            "name_vi": "Anthracite Coffee Seocho",
            "name_fr": "Anthracite Coffee Seocho",
            "description_en": "Industrial-chic coffee roastery offering house-roasted specialty beans and artisanal brews in a spacious setting.",
            "description_ko": "넓은 공간에서 자체 로스팅 스페셜티 원두와 수제 브루를 즐길 수 있는 인더스트리얼 스타일 로스터리입니다.",
            "description_zh_cn": "工业风格的咖啡烘焙馆，在宽敞的空间里提供自家烘焙的精品咖啡豆和手工冲泡咖啡。",
            "description_zh_tw": "工業風格的咖啡烘焙館，在寬敞的空間裡提供自家烘焙的精品咖啡豆和手工沖泡咖啡。",
            "description_ja": "広々とした空間で自家焙煎のスペシャルティコーヒーを楽しめるインダストリアルシックなロースタリー。",
            "description_es": "Tostadería de café industrial-chic que ofrece granos especiales tostados en casa y preparaciones artesanales en un espacio amplio.",
            "description_th": "โรงคั่วกาแฟสไตล์อินดัสเทรียลชิค เสิร์ฟกาแฟพิเศษคั่วเองและชงแบบอาร์ทิซานในพื้นที่กว้างขวาง",
            "description_vi": "Xưởng rang cà phê phong cách công nghiệp với hạt cà phê đặc sản rang tại chỗ trong không gian rộng rãi.",
            "description_fr": "Brûlerie de café au style industriel chic proposant des grains de spécialité torréfiés maison dans un espace spacieux.",
            "category": "cafe",
            "price_range": 2,
            "address": "서울특별시 서초구 방배로 180",
            "latitude": 37.4835,
            "longitude": 127.0130,
            "phone": "02-535-7799",
            "opening_hours": {
                "mon": "09:00-22:00",
                "tue": "09:00-22:00",
                "wed": "09:00-22:00",
                "thu": "09:00-22:00",
                "fri": "09:00-22:00",
                "sat": "10:00-22:00",
                "sun": "10:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Espresso", "name_ko": "에스프레소", "price": 5000},
                {"name_en": "Cold Brew", "name_ko": "콜드 브루", "price": 6500},
                {"name_en": "Flat White", "name_ko": "플랫 화이트", "price": 6000},
                {"name_en": "Banana Bread", "name_ko": "바나나 브레드", "price": 5500},
            ],
            "images": ["/images/placeholder/restaurant_21.jpg"],
            "avg_rating": 4.5,
            "review_count": 148,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Nudake Gangnam",
            "name_ko": "누데이크 강남",
            "name_zh_cn": "Nudake 江南",
            "name_zh_tw": "Nudake 江南",
            "name_ja": "ヌデイク 江南",
            "name_es": "Nudake Gangnam",
            "name_th": "นูเดค คังนัม",
            "name_vi": "Nudake Gangnam",
            "name_fr": "Nudake Gangnam",
            "description_en": "Trendy dessert café by Gentle Monster known for its sculptural cakes, artistic interiors, and unique beverages.",
            "description_ko": "젠틀몬스터가 만든 트렌디 디저트 카페로 조각 케이크와 예술적 인테리어, 유니크한 음료로 유명합니다.",
            "description_zh_cn": "Gentle Monster旗下的潮流甜品咖啡厅，以雕塑蛋糕、艺术内饰和独特饮品闻名。",
            "description_zh_tw": "Gentle Monster旗下的潮流甜品咖啡廳，以雕塑蛋糕、藝術內飾和獨特飲品聞名。",
            "description_ja": "ジェントルモンスターによるトレンディなデザートカフェ。彫刻ケーキ、アート空間、ユニークなドリンクが人気。",
            "description_es": "Café de postres de moda de Gentle Monster conocido por sus pasteles esculturales, interiores artísticos y bebidas únicas.",
            "description_th": "คาเฟ่ขนมหวานสุดทันสมัยของ Gentle Monster มีชื่อเสียงด้านเค้กรูปปั้น ตกแต่งภายในแบบศิลปะ และเครื่องดื่มเฉพาะตัว",
            "description_vi": "Quán cà phê tráng miệng thời thượng của Gentle Monster với bánh điêu khắc, nội thất nghệ thuật và đồ uống độc đáo.",
            "description_fr": "Café de desserts tendance de Gentle Monster connu pour ses gâteaux sculpturaux, intérieurs artistiques et boissons uniques.",
            "category": "cafe",
            "price_range": 4,
            "address": "서울특별시 강남구 도산대로 443",
            "latitude": 37.5210,
            "longitude": 127.0370,
            "phone": "02-515-0801",
            "opening_hours": {
                "mon": "11:00-21:00",
                "tue": "11:00-21:00",
                "wed": "11:00-21:00",
                "thu": "11:00-21:00",
                "fri": "11:00-22:00",
                "sat": "11:00-22:00",
                "sun": "11:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Peak Cake", "name_ko": "피크 케이크", "price": 12000},
                {"name_en": "Nude Latte", "name_ko": "누드 라떼", "price": 7000},
                {"name_en": "Earth Cake", "name_ko": "어스 케이크", "price": 11000},
                {"name_en": "Signature Ice Cream", "name_ko": "시그니처 아이스크림", "price": 8000},
            ],
            "images": ["/images/placeholder/restaurant_22.jpg"],
            "avg_rating": 4.3,
            "review_count": 176,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Fritz Coffee Company Gangnam",
            "name_ko": "프릳츠 커피 컴퍼니 강남점",
            "name_zh_cn": "Fritz咖啡公司 江南店",
            "name_zh_tw": "Fritz咖啡公司 江南店",
            "name_ja": "フリッツコーヒーカンパニー 江南店",
            "name_es": "Fritz Coffee Company Gangnam",
            "name_th": "ฟริตซ์ คอฟฟี่ คอมพานี คังนัม",
            "name_vi": "Fritz Coffee Company Gangnam",
            "name_fr": "Fritz Coffee Company Gangnam",
            "description_en": "Beloved Seoul coffee brand offering freshly baked bread, pastries, and expertly brewed specialty coffee.",
            "description_ko": "갓 구운 빵과 페이스트리, 전문적으로 추출한 스페셜티 커피를 즐길 수 있는 서울 대표 커피 브랜드입니다.",
            "description_zh_cn": "深受喜爱的首尔咖啡品牌，提供新鲜烘焙面包、糕点和精心冲泡的精品咖啡。",
            "description_zh_tw": "深受喜愛的首爾咖啡品牌，提供新鮮烘焙麵包、糕點和精心沖泡的精品咖啡。",
            "description_ja": "焼きたてパンとペストリー、丁寧に淹れたスペシャルティコーヒーを提供するソウルの人気コーヒーブランド。",
            "description_es": "Querida marca de café de Seúl que ofrece pan recién horneado, pastelería y café de especialidad expertamente preparado.",
            "description_th": "แบรนด์กาแฟยอดนิยมของโซล เสิร์ฟขนมปังอบสด เพสตรี้ และกาแฟพิเศษชงอย่างเชี่ยวชาญ",
            "description_vi": "Thương hiệu cà phê yêu thích Seoul với bánh mì nướng tươi, bánh ngọt và cà phê đặc sản pha chuyên nghiệp.",
            "description_fr": "Marque de café bien-aimée de Séoul offrant pains frais, pâtisseries et café de spécialité expertement préparé.",
            "category": "cafe",
            "price_range": 1,
            "address": "서울특별시 강남구 테헤란로 415",
            "latitude": 37.5055,
            "longitude": 127.0525,
            "phone": "02-508-1140",
            "opening_hours": {
                "mon": "07:30-21:00",
                "tue": "07:30-21:00",
                "wed": "07:30-21:00",
                "thu": "07:30-21:00",
                "fri": "07:30-21:00",
                "sat": "08:00-21:00",
                "sun": "08:00-20:00"
            },
            "menu_highlights": [
                {"name_en": "Americano", "name_ko": "아메리카노", "price": 5000},
                {"name_en": "Salt Bread", "name_ko": "소금빵", "price": 3500},
                {"name_en": "Vanilla Latte", "name_ko": "바닐라 라떼", "price": 6500},
                {"name_en": "Egg Tart", "name_ko": "에그타르트", "price": 4000},
                {"name_en": "Iced Einspanner", "name_ko": "아이스 아인슈페너", "price": 7000},
            ],
            "images": ["/images/placeholder/restaurant_23.jpg"],
            "avg_rating": 4.6,
            "review_count": 191,
            "is_active": True,
        },
        # ===================== STREET_FOOD (3) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Gangnam Tteokbokki Town",
            "name_ko": "강남 떡볶이 타운",
            "name_zh_cn": "江南炒年糕城",
            "name_zh_tw": "江南炒年糕城",
            "name_ja": "江南トッポッキタウン",
            "name_es": "Pueblo Tteokbokki de Gangnam",
            "name_th": "คังนัม ต็อกบกกี ทาวน์",
            "name_vi": "Phố Tteokbokki Gangnam",
            "name_fr": "Ville Tteokbokki de Gangnam",
            "description_en": "Bustling street food spot in Gangnam famous for spicy tteokbokki, sundae, and assorted fried snacks.",
            "description_ko": "매콤한 떡볶이, 순대, 각종 튀김으로 유명한 강남의 활기찬 분식집입니다.",
            "description_zh_cn": "江南热闹的街头小吃店，以辣炒年糕、血肠和各种炸小吃闻名。",
            "description_zh_tw": "江南熱鬧的街頭小吃店，以辣炒年糕、血腸和各種炸小吃聞名。",
            "description_ja": "辛いトッポッキ、スンデ、各種フライで有名な江南の活気あるストリートフード店。",
            "description_es": "Concurrido puesto de comida callejera en Gangnam famoso por tteokbokki picante, sundae y variados aperitivos fritos.",
            "description_th": "ร้านสตรีทฟู้ดคึกคักในคังนัม มีชื่อเสียงด้านต็อกบกกีรสเผ็ด ซุนแด และของทอดหลากหลาย",
            "description_vi": "Quán ăn đường phố nhộn nhịp ở Gangnam nổi tiếng với tteokbokki cay, sundae và đồ chiên đa dạng.",
            "description_fr": "Lieu de street food animé à Gangnam célèbre pour ses tteokbokki épicés, sundae et assortiment de beignets.",
            "category": "street_food",
            "price_range": 1,
            "address": "서울특별시 강남구 강남대로 340",
            "latitude": 37.4975,
            "longitude": 127.0280,
            "phone": "02-555-3478",
            "opening_hours": {
                "mon": "10:00-22:00",
                "tue": "10:00-22:00",
                "wed": "10:00-22:00",
                "thu": "10:00-22:00",
                "fri": "10:00-23:00",
                "sat": "10:00-23:00",
                "sun": "10:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Tteokbokki", "name_ko": "떡볶이", "price": 5000},
                {"name_en": "Sundae", "name_ko": "순대", "price": 5000},
                {"name_en": "Fried Dumplings", "name_ko": "튀김만두", "price": 4000},
                {"name_en": "Fish Cake Skewers", "name_ko": "어묵꼬치", "price": 1000},
            ],
            "images": ["/images/placeholder/restaurant_24.jpg"],
            "avg_rating": 4.0,
            "review_count": 134,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Seocho Chicken & Beer",
            "name_ko": "서초 치킨앤비어",
            "name_zh_cn": "瑞草炸鸡啤酒",
            "name_zh_tw": "瑞草炸雞啤酒",
            "name_ja": "瑞草チキン＆ビール",
            "name_es": "Pollo y Cerveza de Seocho",
            "name_th": "ซอโช ชิกเก้น แอนด์ เบียร์",
            "name_vi": "Gà & Bia Seocho",
            "name_fr": "Poulet & Bière de Seocho",
            "description_en": "Popular chimaek (fried chicken & beer) restaurant offering crispy double-fried chicken and draft beer.",
            "description_ko": "바삭한 이중 후라이드 치킨과 생맥주를 즐길 수 있는 인기 치맥 전문점입니다.",
            "description_zh_cn": "人气炸鸡啤酒餐厅，提供酥脆的双炸鸡和生啤酒。",
            "description_zh_tw": "人氣炸雞啤酒餐廳，提供酥脆的雙炸雞和生啤酒。",
            "description_ja": "カリカリの二度揚げチキンと生ビールが楽しめる人気のチメク（チキン＆ビール）レストラン。",
            "description_es": "Popular restaurante de chimaek (pollo frito y cerveza) que ofrece pollo crujiente doblemente frito y cerveza de barril.",
            "description_th": "ร้านชิเมก (ไก่ทอดกับเบียร์) ยอดนิยม เสิร์ฟไก่ทอดกรอบสองครั้งและเบียร์สด",
            "description_vi": "Nhà hàng chimaek (gà rán & bia) nổi tiếng với gà chiên giòn hai lần và bia tươi.",
            "description_fr": "Restaurant populaire de chimaek (poulet frit & bière) offrant du poulet croustillant double-frit et bière pression.",
            "category": "street_food",
            "price_range": 1,
            "address": "서울특별시 서초구 서초대로 256",
            "latitude": 37.4920,
            "longitude": 127.0215,
            "phone": "02-521-9922",
            "opening_hours": {
                "mon": "15:00-02:00",
                "tue": "15:00-02:00",
                "wed": "15:00-02:00",
                "thu": "15:00-02:00",
                "fri": "15:00-03:00",
                "sat": "15:00-03:00",
                "sun": "15:00-01:00"
            },
            "menu_highlights": [
                {"name_en": "Original Fried Chicken", "name_ko": "후라이드 치킨", "price": 18000},
                {"name_en": "Yangnyeom Chicken", "name_ko": "양념 치킨", "price": 19000},
                {"name_en": "Half & Half", "name_ko": "반반 치킨", "price": 19000},
                {"name_en": "Draft Beer", "name_ko": "생맥주", "price": 5000},
            ],
            "images": ["/images/placeholder/restaurant_25.jpg"],
            "avg_rating": 4.1,
            "review_count": 112,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Sindang Hotteok Gangnam",
            "name_ko": "신당호떡 강남점",
            "name_zh_cn": "新堂糖饼 江南店",
            "name_zh_tw": "新堂糖餅 江南店",
            "name_ja": "シンダンホットク 江南店",
            "name_es": "Sindang Hotteok Gangnam",
            "name_th": "ชินดัง โฮต็อก คังนัม",
            "name_vi": "Sindang Hotteok Gangnam",
            "name_fr": "Sindang Hotteok Gangnam",
            "description_en": "Classic Korean street snack stall famous for sweet and crispy hotteok filled with brown sugar and seeds.",
            "description_ko": "흑설탕과 씨앗이 들어간 달콤 바삭한 호떡으로 유명한 한국 전통 길거리 간식 가게입니다.",
            "description_zh_cn": "经典韩国街头小吃摊，以甜蜜酥脆的红糖坚果糖饼闻名。",
            "description_zh_tw": "經典韓國街頭小吃攤，以甜蜜酥脆的紅糖堅果糖餅聞名。",
            "description_ja": "黒砂糖と種子入りの甘くてカリカリなホットクで有名な韓国の定番屋台スナック店。",
            "description_es": "Puesto clásico de snacks callejeros coreanos famoso por hotteok dulce y crujiente relleno de azúcar moreno y semillas.",
            "description_th": "แผงขายของว่างเกาหลีคลาสสิก มีชื่อเสียงด้านโฮต็อกหวานกรอบไส้น้ำตาลทรายแดงและเมล็ดพืช",
            "description_vi": "Quầy ăn vặt đường phố Hàn Quốc nổi tiếng với hotteok ngọt giòn nhân đường nâu và hạt.",
            "description_fr": "Stand classique de snacks de rue coréens célèbre pour ses hotteok sucrés et croustillants fourrés au sucre brun et graines.",
            "category": "street_food",
            "price_range": 1,
            "address": "서울특별시 강남구 봉은사로 112",
            "latitude": 37.5100,
            "longitude": 127.0580,
            "phone": "010-5544-3322",
            "opening_hours": {
                "mon": "11:00-20:00",
                "tue": "11:00-20:00",
                "wed": "11:00-20:00",
                "thu": "11:00-20:00",
                "fri": "11:00-21:00",
                "sat": "10:00-21:00",
                "sun": "10:00-19:00"
            },
            "menu_highlights": [
                {"name_en": "Classic Hotteok", "name_ko": "클래식 호떡", "price": 2000},
                {"name_en": "Cheese Hotteok", "name_ko": "치즈 호떡", "price": 3000},
                {"name_en": "Green Tea Hotteok", "name_ko": "녹차 호떡", "price": 2500},
            ],
            "images": ["/images/placeholder/restaurant_26.jpg"],
            "avg_rating": 4.2,
            "review_count": 89,
            "is_active": True,
        },
        # ===================== HALAL (2) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Halal Kitchen Gangnam",
            "name_ko": "할랄 키친 강남",
            "name_zh_cn": "清真厨房 江南",
            "name_zh_tw": "清真廚房 江南",
            "name_ja": "ハラールキッチン 江南",
            "name_es": "Cocina Halal Gangnam",
            "name_th": "ฮาลาล คิทเช่น คังนัม",
            "name_vi": "Bếp Halal Gangnam",
            "name_fr": "Cuisine Halal Gangnam",
            "description_en": "Certified halal restaurant offering a fusion of Korean and Middle Eastern dishes using halal-certified ingredients.",
            "description_ko": "할랄 인증 식재료로 한식과 중동 요리의 퓨전을 선보이는 할랄 인증 레스토랑입니다.",
            "description_zh_cn": "认证清真餐厅，使用清真认证食材融合韩国和中东菜肴。",
            "description_zh_tw": "認證清真餐廳，使用清真認證食材融合韓國和中東菜餚。",
            "description_ja": "ハラール認証食材を使用し、韓国料理と中東料理の融合を提供するハラール認証レストラン。",
            "description_es": "Restaurante certificado halal que ofrece una fusión de platos coreanos y del Medio Oriente con ingredientes certificados halal.",
            "description_th": "ร้านอาหารฮาลาลที่ได้รับการรับรอง นำเสนอฟิวชั่นอาหารเกาหลีและตะวันออกกลางด้วยวัตถุดิบฮาลาล",
            "description_vi": "Nhà hàng halal được chứng nhận với sự kết hợp ẩm thực Hàn Quốc và Trung Đông từ nguyên liệu halal.",
            "description_fr": "Restaurant certifié halal proposant une fusion de plats coréens et moyen-orientaux avec des ingrédients certifiés halal.",
            "category": "halal",
            "price_range": 3,
            "address": "서울특별시 강남구 역삼로 225",
            "latitude": 37.5035,
            "longitude": 127.0400,
            "phone": "02-568-8844",
            "opening_hours": {
                "mon": "11:00-22:00",
                "tue": "11:00-22:00",
                "wed": "11:00-22:00",
                "thu": "11:00-22:00",
                "fri": "11:00-22:00",
                "sat": "11:00-22:00",
                "sun": "11:00-21:00"
            },
            "menu_highlights": [
                {"name_en": "Halal Bulgogi", "name_ko": "할랄 불고기", "price": 16000},
                {"name_en": "Chicken Shawarma", "name_ko": "치킨 샤와르마", "price": 14000},
                {"name_en": "Lamb Kebab Plate", "name_ko": "양고기 케밥 플레이트", "price": 22000},
                {"name_en": "Hummus & Pita", "name_ko": "후무스 & 피타", "price": 10000},
                {"name_en": "Halal Bibimbap", "name_ko": "할랄 비빔밥", "price": 13000},
            ],
            "images": ["/images/placeholder/restaurant_27.jpg"],
            "avg_rating": 4.1,
            "review_count": 76,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Bukhara Gangnam",
            "name_ko": "부카라 강남",
            "name_zh_cn": "布哈拉 江南",
            "name_zh_tw": "布哈拉 江南",
            "name_ja": "ブカラ 江南",
            "name_es": "Bukhara Gangnam",
            "name_th": "บุคฮาร่า คังนัม",
            "name_vi": "Bukhara Gangnam",
            "name_fr": "Bukhara Gangnam",
            "description_en": "Authentic Indian-Pakistani halal restaurant serving tandoori, biryani, and curries with imported spices.",
            "description_ko": "수입 향신료를 사용한 탄두리, 비리야니, 커리를 선보이는 정통 인도-파키스탄 할랄 레스토랑입니다.",
            "description_zh_cn": "正宗印度-巴基斯坦清真餐厅，供应坦都里、比尔亚尼和咖喱，使用进口香料。",
            "description_zh_tw": "正宗印度-巴基斯坦清真餐廳，供應坦都里、比爾亞尼和咖哩，使用進口香料。",
            "description_ja": "輸入スパイスを使用したタンドリー、ビリヤニ、カレーを提供する本格的なインド・パキスタンハラールレストラン。",
            "description_es": "Auténtico restaurante halal indio-pakistaní que sirve tandoori, biryani y curris con especias importadas.",
            "description_th": "ร้านอาหารฮาลาลอินเดีย-ปากีสถานแท้ เสิร์ฟทันดูรี บิรยานี และแกงกะหรี่ด้วยเครื่องเทศนำเข้า",
            "description_vi": "Nhà hàng halal Ấn Độ-Pakistan chính hiệu với tandoori, biryani và cà ri từ gia vị nhập khẩu.",
            "description_fr": "Authentique restaurant halal indo-pakistanais servant tandoori, biryani et currys avec des épices importées.",
            "category": "halal",
            "price_range": 3,
            "address": "서울특별시 서초구 강남대로 293",
            "latitude": 37.4955,
            "longitude": 127.0270,
            "phone": "02-534-7799",
            "opening_hours": {
                "mon": "11:00-22:00",
                "tue": "11:00-22:00",
                "wed": "11:00-22:00",
                "thu": "11:00-22:00",
                "fri": "11:00-23:00",
                "sat": "11:00-23:00",
                "sun": "11:00-21:30"
            },
            "menu_highlights": [
                {"name_en": "Chicken Biryani", "name_ko": "치킨 비리야니", "price": 16000},
                {"name_en": "Tandoori Chicken", "name_ko": "탄두리 치킨", "price": 22000},
                {"name_en": "Butter Chicken Curry", "name_ko": "버터 치킨 커리", "price": 18000},
                {"name_en": "Garlic Naan", "name_ko": "갈릭 난", "price": 4000},
                {"name_en": "Mango Lassi", "name_ko": "망고 라씨", "price": 6000},
            ],
            "images": ["/images/placeholder/restaurant_28.jpg"],
            "avg_rating": 4.3,
            "review_count": 93,
            "is_active": True,
        },
        # ===================== VEGAN (2) =====================
        {
            "id": str(uuid.uuid4()),
            "name_en": "Plant Gangnam",
            "name_ko": "플랜트 강남",
            "name_zh_cn": "Plant 江南",
            "name_zh_tw": "Plant 江南",
            "name_ja": "プラント 江南",
            "name_es": "Plant Gangnam",
            "name_th": "แพลนท์ คังนัม",
            "name_vi": "Plant Gangnam",
            "name_fr": "Plant Gangnam",
            "description_en": "Upscale plant-based restaurant offering creative vegan dishes with organic, locally sourced ingredients.",
            "description_ko": "유기농 로컬 식재료로 만든 창의적인 비건 요리를 선보이는 고급 플랜트 베이스 레스토랑입니다.",
            "description_zh_cn": "高档植物性餐厅，以有机本地食材提供创意纯素菜肴。",
            "description_zh_tw": "高檔植物性餐廳，以有機本地食材提供創意純素菜餚。",
            "description_ja": "オーガニックの地元食材を使った創造的なビーガン料理を提供する高級プラントベースレストラン。",
            "description_es": "Restaurante vegano de lujo que ofrece platos creativos con ingredientes orgánicos de origen local.",
            "description_th": "ร้านอาหารจากพืชระดับหรู นำเสนออาหารวีแกนสร้างสรรค์จากวัตถุดิบออร์แกนิกท้องถิ่น",
            "description_vi": "Nhà hàng thực vật cao cấp với các món thuần chay sáng tạo từ nguyên liệu hữu cơ địa phương.",
            "description_fr": "Restaurant végétalien haut de gamme proposant des plats créatifs avec des ingrédients biologiques et locaux.",
            "category": "vegan",
            "price_range": 3,
            "address": "서울특별시 강남구 선릉로 152길 18",
            "latitude": 37.5235,
            "longitude": 127.0445,
            "phone": "02-518-7720",
            "opening_hours": {
                "mon": "Closed",
                "tue": "11:30-15:00, 17:30-21:30",
                "wed": "11:30-15:00, 17:30-21:30",
                "thu": "11:30-15:00, 17:30-21:30",
                "fri": "11:30-15:00, 17:30-22:00",
                "sat": "11:00-15:00, 17:30-22:00",
                "sun": "11:00-15:00, 17:30-21:00"
            },
            "menu_highlights": [
                {"name_en": "Seasonal Tasting Course", "name_ko": "계절 코스 메뉴", "price": 65000},
                {"name_en": "Mushroom Bibimbap", "name_ko": "버섯 비빔밥", "price": 18000},
                {"name_en": "Vegan Buddha Bowl", "name_ko": "비건 부다볼", "price": 22000},
                {"name_en": "Raw Chocolate Cake", "name_ko": "로우 초콜릿 케이크", "price": 14000},
            ],
            "images": ["/images/placeholder/restaurant_29.jpg"],
            "avg_rating": 4.5,
            "review_count": 64,
            "is_active": True,
        },
        {
            "id": str(uuid.uuid4()),
            "name_en": "Sprout Seocho",
            "name_ko": "스프라우트 서초",
            "name_zh_cn": "Sprout 瑞草",
            "name_zh_tw": "Sprout 瑞草",
            "name_ja": "スプラウト 瑞草",
            "name_es": "Sprout Seocho",
            "name_th": "สเปราท์ ซอโช",
            "name_vi": "Sprout Seocho",
            "name_fr": "Sprout Seocho",
            "description_en": "Casual vegan café and bakery in Seocho offering wholesome plant-based meals, smoothie bowls, and vegan pastries.",
            "description_ko": "건강한 비건 식사, 스무디볼, 비건 페이스트리를 제공하는 서초의 캐주얼 비건 카페 겸 베이커리입니다.",
            "description_zh_cn": "位于瑞草的休闲素食咖啡厅和面包店，提供健康的植物餐、冰沙碗和素食糕点。",
            "description_zh_tw": "位於瑞草的休閒素食咖啡廳和麵包店，提供健康的植物餐、冰沙碗和素食糕點。",
            "description_ja": "ヘルシーなプラントベースの食事、スムージーボウル、ビーガンペストリーを提供する瑞草のカジュアルビーガンカフェ＆ベーカリー。",
            "description_es": "Café y panadería vegana casual en Seocho que ofrece comidas saludables a base de plantas, smoothie bowls y pastelería vegana.",
            "description_th": "คาเฟ่และเบเกอรี่วีแกนแบบสบายๆ ในซอโช เสิร์ฟอาหารจากพืชเพื่อสุขภาพ สมูทตี้โบว์ล และเพสตรี้วีแกน",
            "description_vi": "Quán cà phê và tiệm bánh thuần chay thoải mái ở Seocho với bữa ăn thực vật, smoothie bowl và bánh ngọt thuần chay.",
            "description_fr": "Café et boulangerie végétaliens décontractés à Seocho offrant des repas sains à base de plantes, smoothie bowls et pâtisseries véganes.",
            "category": "vegan",
            "price_range": 1,
            "address": "서울특별시 서초구 효령로 304",
            "latitude": 37.4870,
            "longitude": 127.0070,
            "phone": "02-582-1133",
            "opening_hours": {
                "mon": "09:00-20:00",
                "tue": "09:00-20:00",
                "wed": "09:00-20:00",
                "thu": "09:00-20:00",
                "fri": "09:00-21:00",
                "sat": "10:00-21:00",
                "sun": "10:00-19:00"
            },
            "menu_highlights": [
                {"name_en": "Açaí Smoothie Bowl", "name_ko": "아사이 스무디볼", "price": 13000},
                {"name_en": "Avocado Toast", "name_ko": "아보카도 토스트", "price": 11000},
                {"name_en": "Vegan Banana Muffin", "name_ko": "비건 바나나 머핀", "price": 5000},
                {"name_en": "Green Detox Juice", "name_ko": "그린 디톡스 주스", "price": 8000},
                {"name_en": "Tofu Salad Bowl", "name_ko": "두부 샐러드 볼", "price": 14000},
            ],
            "images": ["/images/placeholder/restaurant_30.jpg"],
            "avg_rating": 4.4,
            "review_count": 58,
            "is_active": True,
        },
    ]
